name: BelarionEnchants
version: 1.0.0
main: fr.belarion.enchants.BelarionEnchants
author: Belarion
description: Systeme complet de Table d'Enchantement Emeraude et d'Enclume Emeraude (Paper/Spigot 1.8.8).

commands:
  enchanttable:
    description: Donne le bloc de l'Emerald Enchanting Table.
    usage: /enchanttable
    permission: belarionenchants.admin
  enchantanvil:
    description: Donne le bloc de l'Emerald Anvil.
    usage: /enchantanvil
    permission: belarionenchants.admin
  belarionenchants:
    description: Commande principale du plugin (reload, etc).
    usage: /belarionenchants <reload>
    permission: belarionenchants.admin
    aliases: [bel, benchants]
  enchants:
    description: Ouvre la Bibliotheque des Custom Enchants.
    usage: /enchants
    permission: blarionenchants.command.enchants
    aliases: [enchant, customenchants, customenchant]

permissions:
  belarionenchants.admin:
    description: Acces aux commandes admin de BelarionEnchants
    default: op
  blarionenchants.command.enchants:
    description: Autorise l'ouverture de la Bibliotheque des Custom Enchants via /enchants.
    default: true
