name: BelarionEnchants
version: 0.1.0
main: fr.belarion.enchants.BelarionEnchants
api-version: '1.21'
author: Belarion
description: Table d'enchantement custom (émeraude) et enchants custom pour Belarion.

commands:
  enchanttable:
    description: Donne un bloc de table d'enchantement custom (émeraude).
    usage: /enchanttable
    permission: belarionenchants.admin
  enchantanvil:
    description: Donne le bloc d'Enclume en Émeraude.
    usage: /enchantanvil
    permission: belarionenchants.admin
  emeralditem:
    description: Donne un item émeraude custom (sword, hammer).
    usage: /emeralditem <sword|hammer>
    permission: belarionenchants.admin

permissions:
  belarionenchants.admin:
    description: Accès aux commandes admin de BelarionEnchants
    default: op
