name: BelarionEnchants
version: 0.2.0
main: fr.belarion.enchants.BelarionEnchants
author: Belarion
description: Emerald Enchanting Table et Emerald Anvil pour Belarion (1.8.8).

commands:
  enchanttable:
    description: Donne le bloc de l'Emerald Enchanting Table.
    usage: /enchanttable
    permission: belarionenchants.admin
  enchantanvil:
    description: Donne le bloc de l'Emerald Anvil.
    usage: /enchantanvil
    permission: belarionenchants.admin
  emeralditem:
    description: Donne un item emeraude custom.
    usage: /emeralditem <sword|hammer|boots>
    permission: belarionenchants.admin

permissions:
  belarionenchants.admin:
    description: Acces aux commandes admin de BelarionEnchants
    default: op
